services:
  - type: web
    name: media-insights-platform
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main_dashboard.py --server.port $PORT --server.address 0.0.0.0
    pythonVersion: 3.12.3
